name: Ejecutar script meteorológico para que comience a funcionar otra vez


on:
  schedule:
    - cron: '30 11 * * *' # Ejecuta todos los días a las 11:30 AM UTC
  workflow_dispatch: # Permite ejecuciones manuales desde GitHub

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python ./charo.py
