name: Depurar variables de entorno

on:
  workflow_dispatch: # Permite ejecuciones manuales desde GitHub

jobs:
  debug_environment_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Print environment variables for debugging
      run: |
        echo "TELEGRAM_TOKEN: $TELEGRAM_TOKEN"
        echo "TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID"
        echo "API_KEY: $API_KEY"
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        API_KEY: ${{ secrets.API_KEY }}


